name: Egen-CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.402"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet cake --target build

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.402"

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet cake --target build

      - name: Test
        run: dotnet cake --target test

  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.402"

      - name: Build Docker Image
        run: dotnet cake --target docker-build
